apiVersion: v1
kind: Service
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  type: ClusterIP
  ports:
  - name: tcp-receiver
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: udp-receiver-tcp
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: udp-receiver-udp
    protocol: UDP
    port: 8082
    targetPort: 8082
  selector:
    app: receiver
