apiVersion: v1
kind: Service
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  type: NodePort
  ports:
  - name: tcp-receiver
    protocol: TCP
    port: {{ .Values.cmdOptions.tcpPort }}
    targetPort: {{ .Values.cmdOptions.tcpPort }}
    nodePort: 30001
  - name: udp-receiver-tcp
    protocol: TCP
    port: {{ .Values.cmdOptions.udpPort }}
    targetPort: {{ .Values.cmdOptions.udpPort }}
    nodePort: 30002
  - name: udp-receiver-udp
    protocol: UDP
    port: {{ .Values.cmdOptions.udpPort }}
    targetPort: {{ .Values.cmdOptions.udpPort }}
    nodePort: 30002
  selector:
    app: receiver
